# NumPy
**NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.**

In [1]:
import numpy as np

In [3]:
# From python list
lst = [1,2,3]
lst

[1, 2, 3]

In [4]:
np.array(lst)

array([1, 2, 3])

In [5]:
#From list of lists
mat = [[1,2,3],[3,4,5],[6,7,8]]
mat

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [6]:
np.array(mat)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

### Built-in methods for Creating Arrays
###  arange()

In [9]:
# Creating array by built-in methods: There are lots of built-in ways to generate Arrays
# 1. arange method: it returns evenly spaced values within given interval

np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,3)

array([0, 3, 6, 9])

### zeroes and ones

In [11]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### linspace
 it return evenly spaced numbers over a specified interval. This should not be confused with arange(). From the below example it is clear that linspace returns evenly spaced array(whatever the space between two consective passed as arg) where as arange() returns the array of mentioned step value

In [23]:
lins_arr = np.linspace(0,10,3)
arr = np.arange(0,10,3) 
print(lins_arr,lins_arr.dtype)
print(arr,arr.dtype)

[ 0.  5. 10.] float64
[0 3 6 9] int32


### eye  (Diagonal matrix)

In [24]:
# Creating Diagonal matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(3,dtype = 'i')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

### Random
 There are ways which numpy offers to create random number arrays
### rand

In [26]:
# rand creates an array of the given shape and populate it with random samples from a uniform distribution over [0,1]
np.random.rand(3)

array([0.16834124, 0.60259696, 0.56436213])

In [28]:
np.random.rand(4,4)

array([[0.79699399, 0.50013974, 0.50477871, 0.60581223],
       [0.41641541, 0.5965071 , 0.21089494, 0.63020913],
       [0.72079185, 0.56427965, 0.03067079, 0.9337545 ],
       [0.04883276, 0.67565958, 0.13416331, 0.64444797]])

### randn
return a sample (or samples) from the 'standard normal distribution'. Unlike rand which is uniform

In [29]:
np.random.randn(2)

array([-1.04676782,  0.33886241])

### randint
returns random integers from low (inclusive) and high(exclusive)

In [33]:
np.random.randint(1,100) #run twice or thrice to see the output change

75

In [35]:
np.random.randint(10,100,15)  # third argument is no. of elements in an array

array([18, 12, 74, 96, 83, 52, 56, 43, 69, 94, 18, 56, 76, 11, 40])

# Array Attributes and Methods

In [37]:
arr = np.arange(20)
ranarr = np.random.randint(0,50,10)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
ranarr

array([30, 37, 18, 26,  2, 16,  5, 41, 11, 18])

### reshape()
 it returns the array containing the same data with a new shape

In [41]:
arr.reshape(5,4)  # the passed arguments is simply size of matrix we can say 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### max, min , argmax, argmin
These methods are useful for finding the max or min values of an array . Or to find their index locations using argmin or argmax

In [42]:
ranarr

array([30, 37, 18, 26,  2, 16,  5, 41, 11, 18])

In [43]:
max(ranarr)

41

In [44]:
min(ranarr)

2

In [46]:
ranarr.argmin()

4

In [47]:
ranarr.argmax()

7

### Shape
Shape is an attribute that arrays have(it is not a method)

In [18]:
import numpy as np
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
arr.shape

(20,)

so 'arr' is a Vector . Let's reshape it into a matrix

In [54]:
arr.reshape(4,5) #size passed must be equal to the no. of elements otherwise it throws an error

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

notice the two sets of brackets

In [57]:
arr #as shape is attribute not a method thus change is not permanant

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [62]:
reshaped_arr = arr.reshape(5,4) #making it permenant

In [63]:
reshaped_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [61]:
reshaped_arr.shape

(5, 4)

### dtype
used to grab or set the datatype of an array

In [80]:
arr.dtype

dtype('float32')

In [81]:
arr.dtype = 'i'

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int32)

In [83]:
arr.dtype

dtype('int32')

# NumPy Operations
### Airthmetic

In [84]:
ar = np.arange(0,6)

In [86]:
ar

array([0, 1, 2, 3, 4, 5])

In [87]:
ar + ar

array([ 0,  2,  4,  6,  8, 10])

In [88]:
ar - ar

array([0, 0, 0, 0, 0, 0])

In [89]:
ar * ar

array([ 0,  1,  4,  9, 16, 25])

In [91]:
ar / ar      # we cannot divide by zero thus we will get warning

<ipython-input-91-b5867758b6df>:1: RuntimeWarning: invalid value encountered in true_divide
  ar / ar      # we cannot divide by zero thus we will get warning


array([nan,  1.,  1.,  1.,  1.,  1.])

In [93]:
1 / ar   # as 1/0 is infinity so we will get warning and inf no.

<ipython-input-93-2c458fa70915>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / ar   # as 1/0 is infinity so we will get warning and inf no.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       ])

In [96]:
ar**3

array([  0,   1,   8,  27,  64, 125], dtype=int32)

### Universal Array Functions
these are essentially just mathematical operations we can use to perform across the array

In [97]:
# Square roots
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [98]:
# Exponential (e^)
np.exp(ar)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [99]:
# logarithm 
np.log(ar)

<ipython-input-99-4f66a47a8aaa>:2: RuntimeWarning: divide by zero encountered in log
  np.log(ar)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

In [100]:
# Sine
np.sin(ar)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [101]:
np.max(ar)

5

there are lot of functions like these which we can check out in python documentation

# NumPy Indexing and Selection

In [103]:
arr = np.arange(0,11)

In [104]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Bracket Indexing and Selection

In [106]:
arr[4] # get value at index 4

4

In [108]:
arr [3:6]   # get a range of values from index 3 to index 5

array([3, 4, 5])

### Broadcasting
*Numpy arrays differ from a normal Python list because of their ability to broadcast*

In [109]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
arr[0:4] = 30 # Setting a value with index range (Broadcasting)

In [111]:
arr

array([30, 30, 30, 30,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr = np.arange(0,11) #resetting the array back
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slicing the array

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [117]:
slice_of_arr[:] = 20
slice_of_arr

array([20, 20, 20, 20, 20])

In [118]:
arr

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9, 10])

note that changes are done to original array too. to get copy of it we proceed as

In [119]:
copy_of_arr = arr.copy()
copy_of_arr

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9, 10])

### Indexing a 2D array(matrices)
The general format is **arr_2d[row][col] or arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [121]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
mat[2]   # grabbing row 3

array([7, 8, 9])

In [127]:
mat[2][2]  # grabbing element of row 3 and column 3

9

In [129]:
#comma notation
mat[2,2]

9

In [130]:
mat[1,2]

6

In [134]:
# Submatrix
mat[1:,1:]  # ':' means all i,e row of index 1 to all rows and same goes for column

array([[5, 6],
       [8, 9]])

### Fancy Indexing
Fancy indexing allows us to select entire rows or columns out of order

In [1]:
import numpy as np

In [2]:
ar2d = np.zeros((5,5))
ar2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
arr_len = ar2d.shape[1]
arr_len
ar2d.shape[1]
#type(ar2d.shape)

5

In [12]:
for i in range(arr_len):
    ar2d[i] = i       # setting up an array row wise

ar2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

Now Fancy indexing allows the following

In [13]:
ar2d[[2,0,4]]

array([[2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0.],
       [4., 4., 4., 4., 4.]])

In [14]:
ar2d[[4,3,0,2]]

array([[4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2.]])

# NumPy Exercise

In [59]:
# Create an array of 10 zeroes
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
#Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
#create an array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [25]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [26]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
# Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

array([0.66722363])

In [30]:
# Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(26)

array([-0.34582465,  1.02195826,  1.44917457,  1.84605217, -0.34100465,
        0.09895751,  0.32410827, -0.46400038, -0.42440542, -0.6089496 ,
       -0.89540647,  0.40054199,  0.35351145,  0.13643213,  0.56242279,
       -0.23835814,  1.2534897 , -0.08208083,  0.95359084, -0.07386752,
        1.51086287, -0.53976365, -1.74600577, -1.19141339,  0.2059795 ,
        0.65040366])

In [38]:
# Create the following matrix
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [41]:
# Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [9]:
# Numpy Indexing and selections questions
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [11]:
mat[3,4]

20

In [12]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [13]:
mat[4]

array([21, 22, 23, 24, 25])

In [14]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
np.sum(mat)

325

In [16]:
np.std(mat)

7.211102550927978

In [19]:
# column wise sum of matrix
np.sum(mat,axis = 0)

array([55, 60, 65, 70, 75])

# Thank You